#!/usr/bin/env bash
#
# reset.sh — Power-cycle the BeagleBone Black USB port via uhubctl
#
# ============================================================================
#  USAGE
# ============================================================================
#
#  Prerequisites:
#    - uhubctl installed:  sudo apt install uhubctl
#    - A USB hub that supports per-port power switching ("smart hub").
#      Most cheap hubs do NOT — Genesys Logic (05e3:0608) and some
#      Terminus hubs are known to work. Check with: sudo uhubctl
#    - sudo access (uhubctl needs root to toggle port power)
#
#  First run (interactive discovery):
#    ./reset.sh
#      1. Prints lsusb, lsusb -t, and sudo uhubctl output
#      2. Asks you to identify the hub location and port number
#         where your BBB (or its FTDI serial adapter) is connected
#      3. Verifies uhubctl can control that hub:port
#      4. Saves the choice to ~/.config/reset-usb.conf
#      5. Power-cycles the port (off → 2s pause → on)
#
#  Subsequent runs (automatic):
#    ./reset.sh
#      Reads ~/.config/reset-usb.conf and immediately power-cycles.
#      No prompts, no discovery.
#
#  Re-discover (if you move the BBB to a different port/hub):
#    rm ~/.config/reset-usb.conf
#    ./reset.sh
#
#  Example first-run session:
#    $ ./reset.sh
#    ==> No saved config found. Running discovery...
#    ...
#    Smart hubs visible to uhubctl:
#      Current status for hub 1-1 [0bda:5411 ...]
#        Port 1: 0503 power highspeed ...
#        Port 2: 0100 power
#        Port 3: 0503 power highspeed ... [0403:6001 FTDI FT232R]
#        Port 4: 0100 power
#    ...
#    Enter hub location (e.g. 1-1, 1-3, 2-0): 1-1
#    Enter port number  (e.g. 1, 2, 3, 4):    3
#    ==> Saved config to ~/.config/reset-usb.conf
#    ==> Power OFF / Waiting 2s... / Power ON
#    ==> Done.
#
set -euo pipefail

PAUSE_SEC=3
CONF="$HOME/.config/reset-usb.conf"

# --- Saved config: skip discovery if we already know the hub:port ---
if [ -f "$CONF" ]; then
    source "$CONF"
    echo "==> Using saved config: hub=${HUB_LOC} port=${HUB_PORT}"
    echo "    (delete ${CONF} to re-discover)"
    echo ""
    echo "==> Power OFF"
    sudo uhubctl -l "$HUB_LOC" -p "$HUB_PORT" -a off || true
    echo ""
    echo "==> Waiting ${PAUSE_SEC}s..."
    sleep "$PAUSE_SEC"
    echo ""
    echo "==> Power ON"
    sudo uhubctl -l "$HUB_LOC" -p "$HUB_PORT" -a on || true
    echo ""
    echo "==> Done."
    exit 0
fi

# --- First run: discover smart hubs and let user pick ---
echo "==> No saved config found. Running discovery..."
echo ""
echo "============================================"
echo "  All USB devices (lsusb):"
echo "============================================"
lsusb
echo ""
echo "============================================"
echo "  USB tree (lsusb -t):"
echo "============================================"
lsusb -t
echo ""
echo "============================================"
echo "  Smart hubs visible to uhubctl:"
echo "============================================"
echo ""

# Capture uhubctl output and parse hub:port pairs
UHUBCTL_OUTPUT=$(sudo uhubctl 2>&1) || true
echo "$UHUBCTL_OUTPUT"

if echo "$UHUBCTL_OUTPUT" | grep -q "No compatible"; then
    echo ""
    echo "ERROR: uhubctl found no compatible smart hubs."
    echo "       Your USB hub may not support per-port power switching."
    exit 1
fi

echo ""
echo "============================================"
echo "  Pick the hub and port for your BBB"
echo "============================================"
echo ""
echo "  Look at the uhubctl output above. Find the port that has your"
echo "  BeagleBone Black (likely an FTDI device) or the port whose"
echo "  power you want to cycle."
echo ""

read -rp "  Enter hub location (e.g. 1-1, 1-3, 2-0): " HUB_LOC
read -rp "  Enter port number  (e.g. 1, 2, 3, 4):    " HUB_PORT

if [ -z "$HUB_LOC" ] || [ -z "$HUB_PORT" ]; then
    echo "ERROR: hub location and port are required."
    exit 1
fi

# Verify it works
echo ""
echo "==> Testing: uhubctl -l ${HUB_LOC} -p ${HUB_PORT} ..."
if ! sudo uhubctl -l "$HUB_LOC" -p "$HUB_PORT"; then
    echo ""
    echo "ERROR: uhubctl cannot control hub=${HUB_LOC} port=${HUB_PORT}."
    echo "       Try a different hub location from the output above."
    exit 1
fi

# Save for next time
mkdir -p "$(dirname "$CONF")"
cat > "$CONF" <<EOF
# Auto-generated by reset.sh — delete this file to re-discover
HUB_LOC="${HUB_LOC}"
HUB_PORT="${HUB_PORT}"
EOF
echo ""
echo "==> Saved config to ${CONF}"

# Power cycle
echo ""
echo "==> Power OFF"
sudo uhubctl -l "$HUB_LOC" -p "$HUB_PORT" -a off || true

echo ""
echo "==> Waiting ${PAUSE_SEC}s..."
sleep "$PAUSE_SEC"

echo ""
echo "==> Power ON"
sudo uhubctl -l "$HUB_LOC" -p "$HUB_PORT" -a on || true

echo ""
echo "==> Done. USB port power-cycled."

# ============================================================================
#  USB DISCOVERY CHEAT SHEET
# ============================================================================
#
#  --- List all USB devices ---
#    lsusb                              # short summary of every USB device
#    lsusb -v                           # verbose (all descriptors)
#    lsusb -t                           # tree view showing hub topology
#
#  --- Filter by vendor:product ID ---
#    lsusb -d 0403:6001                 # find FTDI FT232 (BBB serial)
#    lsusb -d 0403:                     # all FTDI devices (any product)
#    lsusb -d :6015                     # any vendor, product 6015
#
#  --- Filter by bus/device number ---
#    lsusb -s 001:011                   # bus 1, device 11
#    lsusb -s 001:                      # all devices on bus 1
#
#  --- Detailed info for one device ---
#    lsusb -v -d 0403:6001             # full descriptor dump
#    lsusb -v -s 001:011               # same, by bus:dev
#    usb-devices                        # kernel's view (no root needed)
#
#  --- sysfs exploration ---
#    ls /sys/bus/usb/devices/           # all USB device paths
#    cat /sys/bus/usb/devices/1-3.4/product      # product string
#    cat /sys/bus/usb/devices/1-3.4/idVendor     # vendor ID
#    cat /sys/bus/usb/devices/1-3.4/idProduct    # product ID
#    cat /sys/bus/usb/devices/1-3.4/serial       # serial number
#    cat /sys/bus/usb/devices/1-3.4/manufacturer # manufacturer string
#
#  --- Find device path in sysfs by vendor:product ---
#    grep -rl '0403' /sys/bus/usb/devices/*/idVendor
#    for d in /sys/bus/usb/devices/*/; do
#      [ -f "$d/idVendor" ] && \
#      [ "$(cat "$d/idVendor")" = "0403" ] && \
#      echo "$d  $(cat "$d/product" 2>/dev/null)"
#    done
#
#  --- Find which ttyUSB a device maps to ---
#    ls /dev/ttyUSB*                    # list serial ports
#    dmesg | grep ttyUSB               # see assignment messages
#    udevadm info -q all -n /dev/ttyUSB0 | grep VENDOR
#    udevadm info --attribute-walk -n /dev/ttyUSB0  # full attr chain
#
#  --- uhubctl commands ---
#    uhubctl                            # show all smart hubs + port status
#    uhubctl -l 1-3.4                   # show specific hub location
#    uhubctl -n 0403                    # filter by vendor ID
#    uhubctl -s "FTDI"                  # search by device description
#    uhubctl -a off  -l 1-3.4 -p 1     # turn OFF  port 1 on hub 1-3.4
#    uhubctl -a on   -l 1-3.4 -p 1     # turn ON   port 1 on hub 1-3.4
#    uhubctl -a cycle -l 1-3.4 -p 1 -d 2  # cycle: off, wait 2s, on
#    uhubctl -a cycle -l 1-3.4 -p 1 -R    # cycle + reset hub after on
#    uhubctl -a off -l 1-3.4 -p 1 -r 3    # repeat off 3 times (stubborn devices)
#
#  --- Find which hub port a device is on ---
#    lsusb -t                           # tree with port numbers
#    # Example output:
#    #   /:  Bus 01.Port 1: Dev 1, Class=root_hub
#    #       |__ Port 3: Dev 4, ... Terminus Technology Inc.
#    #           |__ Port 4: Dev 11, ... FTDI FT232
#    # → hub location = 1-3, device is on port 4 → uhubctl -l 1-3 -p 4
#
#  --- Combine: find hub+port for a known vendor ---
#    # 1) get bus-port path from sysfs:
#    for d in /sys/bus/usb/devices/*/; do
#      [ -f "$d/idVendor" ] || continue
#      v=$(cat "$d/idVendor"); p=$(cat "$d/idProduct")
#      if [ "$v" = "0403" ]; then
#        echo "$(basename "$d")  $v:$p  $(cat "$d/product" 2>/dev/null)"
#      fi
#    done
#    # 2) The path (e.g. 1-3.4) tells you: bus 1, port 3 on root hub,
#    #    port 4 on child hub. Parent hub = 1-3, port = 4.
#
# ============================================================================

