#!/bin/bash
#
# config.sh — Single-point config loader for all board scripts.
#
# Source this file from any script to pick up user settings:
#   SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
#   . "$SCRIPT_DIR/config.sh"
#
# Config file location: ~/.config/bbb_buildroot_cfg
# Generated by: make bbb (or make <board> in the future)
# Format: plain shell KEY=VALUE, one per line.
#
# Precedence (highest wins):
#   1. Environment variables (CLI: BOARD=10.0.0.5 make kernel-deploy)
#   2. Config file (~/.config/bbb_buildroot_cfg)
#   3. Fallback defaults (defined below)
#
# To add a new config key:
#   1. Add a fallback default line below
#   2. Add it to the template in the Makefile's board target (make bbb)
#   That's it — every script that sources this file gets it automatically.
#

BBB_CFG="${HOME}/.config/bbb_buildroot_cfg"

# ---------------------------------------------------------------------------
# Load config with correct precedence: env > config file > fallback default.
#
# The config file uses plain assignments (BOARD=192.168.1.100) which would
# clobber env vars. To preserve env > file precedence, we snapshot any
# env-set values before sourcing, then restore them after. This way:
#   BOARD=10.0.0.5 ./scripts/kernel-deploy.sh   ← env wins
#   (nothing set)                                 ← file wins
#   (no file either)                              ← fallback default wins
# ---------------------------------------------------------------------------

# Snapshot: remember which config vars the caller already set.
_cfg_save() { eval "_cfg_saved_$1=\"\${$1:-}\"  _cfg_had_$1=\${$1+yes}"; }
_cfg_restore() {
    eval "if [ \"\${_cfg_had_$1:-}\" = yes ]; then $1=\"\$_cfg_saved_$1\"; fi"
    eval "unset _cfg_saved_$1 _cfg_had_$1"
}

_cfg_save BOARD_NAME; _cfg_save BOARD; _cfg_save BOARD_PASS; _cfg_save DTB
_cfg_save TFTP_DIR; _cfg_save OUTPUT_DIR; _cfg_save HOST_IP; _cfg_save NFS_DIR

if [ -f "$BBB_CFG" ]; then
    _config_had_u=false
    case "$-" in *u*) _config_had_u=true; set +u;; esac
    . "$BBB_CFG"
    $_config_had_u && set -u
    unset _config_had_u
fi

# Restore env overrides (env wins over file).
_cfg_restore BOARD_NAME; _cfg_restore BOARD; _cfg_restore BOARD_PASS; _cfg_restore DTB
_cfg_restore TFTP_DIR; _cfg_restore OUTPUT_DIR; _cfg_restore HOST_IP; _cfg_restore NFS_DIR
unset -f _cfg_save _cfg_restore

# --- Fallback defaults ----------------------------------------------------
# These apply only when neither the env nor the config file sets the value.

BOARD_NAME="${BOARD_NAME:-}"
BOARD="${BOARD:-}"
BOARD_PASS="${BOARD_PASS:-root}"
DTB="${DTB:-am335x-boneblack.dtb}"
TFTP_DIR="${TFTP_DIR:-/srv/tftp}"
OUTPUT_DIR="${OUTPUT_DIR:-output}"
# HOST_IP: auto-detect from the route to BOARD if not explicitly set.
# `ip route get <BOARD>` returns the source IP the kernel would use.
if [ -z "${HOST_IP:-}" ] && [ -n "${BOARD:-}" ]; then
    HOST_IP="$(ip route get "$BOARD" 2>/dev/null | sed -n 's/.* src \([^ ]*\).*/\1/p')"
fi
HOST_IP="${HOST_IP:-}"
NFS_DIR="${NFS_DIR:-$(pwd)/output/target}"
